use virtualdc;

CREATE TABLE morto (
	CODFUN INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(40) NOT NULL,
	DEPTO CHAR(2),
	FUNCAO CHAR(20),
	SALARIO DECIMAL(10,2),
	ADMISSAO DATE
);

INSERT INTO MORTO SELECT CODFUN, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO FROM cadfun WHERE CODFUN = 1;


-- Bucas específicas


SELECT * FROM morto;

-- Busca a partir do insert do cadfun em morto
SELECT * FROM cadfun WHERE SALARIO = (SELECT SALARIO FROM morto);
SELECT * FROM cadfun WHERE DEPTO = (SELECT DEPTO FROM morto);

-- Bucas nos DEPTOS 6 e 9
SELECT NOME, DEPTO FROM cadfun WHERE DEPTO IN('6', '9') ORDER BY DEPTO;
SELECT NOME, DEPTO FROM cadfun WHERE DEPTO NOT IN('6', '9') ORDER BY DEPTO;

-- Busca por chars (LIKE) específicos nos nomes
-- % = Resto
SELECT NOME FROM cadfun WHERE NOME LIKE 'A%';
SELECT NOME FROM cadfun WHERE NOME LIKE '_A%';
SELECT NOME FROM cadfun WHERE NOME LIKE '%A%';
SELECT NOME FROM cadfun WHERE NOME LIKE '%A';
SELECT NOME FROM cadfun WHERE NOME LIKE '%An%';
SELECT NOME FROM cadfun WHERE NOME NOT LIKE '%An%';
SELECT NOME, SALARIO FROM cadfun WHERE SALARIO LIKE '_5%0';


-- EXERCÍCIOS

-- EXC 07
UPDATE cadfun SET SALARIO = SALARIO + 250 FROM cadfun
SELECT CODFUN, NOME, SALARIO FROM cadfun;

-- EXC 08
UPDATE cadfun SET SALARIO = SALARIO * 0.925 FROM cadfun;
SELECT CODFUN, NOME, SALARIO FROM cadfun;

-- EXC 09
SELECT * FROM cadfun WHERE FUNCAO = 'Vendedor';

-- EXC 10
SELECT * FROM cadfun WHERE (SALARIO >= 70000)

-- EXC 11
SELECT * FROM cadfun WHERE (SALARIO > 70000)

-- EXC 12
SELECT * FROM cadfun WHERE (SALARIO < 70000)

-- EXC 13
SELECT * FROM cadfun WHERE (SALARIO = 68163.25)

-- EXC 14
SELECT * FROM cadfun WHERE (FUNCAO = 'Programadora') OR (FUNCAO = 'Vendedor');

-- EXC 15
SELECT * FROM cadfun WHERE (FUNCAO = 'Programadora' AND (SALARIO > 250000) OR FUNCAO = 'Vendedor' AND (SALARIO > 76000));

-- EXC 16
SELECT * FROM cadfun WHERE (NOT FUNCAO = 'Programadora' AND NOT FUNCAO = 'Vendedor');

-- EXC 17
SELECT * FROM cadfun WHERE (FILHOS >= 1);

-- EXC 18
SELECT * FROM cadfun WHERE (FILHOS >= 1 AND (SALARIO < 75000));

-- EXC 19
SELECT * FROM cadfun WHERE (FILHOS < 2) OR (FILHOS > 3) 

-- EXC 20
SELECT * FROM cadfun WHERE (FILHOS < 2) OR (FILHOS > 3) 

-- EXC 21
SELECT * FROM cadfun WHERE FILHOS IN ('2', '3');

-- EXC 22
SELECT * FROM cadfun WHERE NOME LIKE '%AN%';

-- EXC 23
SELECT * FROM cadfun WHERE NOME LIKE 'AN%';

-- EXC 24
SELECT * FROM cadfun WHERE NOME LIKE '%AND%';

-- EXC 25
SELECT NOME, DEPTO FROM cadfun WHERE (FUNCAO = 'Programadora' OR FUNCAO = 'Vendedor');

-- EXC 26 
SELECT CODFUN, NOME, DEPTO FROM cadfun WHERE (CODFUN = '1' OR CODFUN = '18' OR CODFUN = '59');

-- EXC 27
SELECT NOME, DEPTO FROM cadfun WHERE NOT DEPTO = '10';

-- EXC 28
SELECT * FROM cadfun WHERE NOME LIKE '%AND%';

-- EXC 29 
SELECT * FROM cadfun WHERE SALARIO != 68163.25;