use virtualdc;

-- Agrupamento de dados usa a clásula GROUP BY

SELECT DEPTO, COUNT(*) FROM cadfun GROUP BY DEPTO;
SELECT DEPTO, SUM(SALARIO) FROM cadfun GROUP BY DEPTO;
SELECT DEPTO, SUM(SALARIO) FROM cadfun WHERE DEPTO IN ('10', '5') GROUP BY DEPTO;
SELECT DEPTO, SUM(SALARIO) FROM cadfun GROUP BY DEPTO HAVING SUM(SALARIO) > 20000;


-- //
-- UNIÃO DE DADOS (JOINS) -  União de uma ou mais colunas via múltiplos comandos SELECT
-- Usam se os operadores UNION ou UNION ALL
ALTER TABLE morto ADD DATANASCIMENTO DATE, FILHOS SMALLINT;
ALTER TABLE morto ALTER COLUMN FILHOS SMALLINT;

INSERT INTO morto 
	SELECT CODFUN, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, DATANASCIMENTO, FILHOS 
	FROM cadfun WHERE CODFUN = 59;

INSERT INTO morto SELECT * FROM cadfun WHERE CODFUN IN (63, 65, 67, 70, 72, 74, 80);

SELECT * FROM morto;

SELECT CODFUN, NOME FROM cadfun UNION SELECT CODFUN, NOME FROM morto;

CREATE TABLE cliente(
	CODCLI CHAR(3) NOT NULL PRIMARY KEY,
	NOME CHAR(40) NOT NULL,
	ENDERECO CHAR(50) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	CEP CHAR(9) NOT NULL
)
INSERT INTO cliente VALUES ('250', 'BANCO BARCA S/A', 'R. VITO, 34', 'SÃO SEBASTIÃO', 'CE', '62380-000');
SELECT * FROM cliente;


CREATE TABLE venda(
	DUPLIC CHAR(6) NOT NULL PRIMARY KEY,
	VALOR DECIMAL(10, 2) NOT NULL,
	VENCTO DATE NOT NULL,
	CODCLI CHAR(3) NOT NULL
)
INSERT INTO venda VALUES('230001', 1300.0, '10-04-2022', '340');
SELECT * FROM venda;

-- Ex de JOIN (pega dos)
SELECT venda.DUPLIC, cliente.nome FROM cliente, venda WHERE cliente.CODCLI = venda.CODCLI;

select cliente.NOME, venda.DUPLIC, venda.VALOR FROM cliente, venda WHERE cliente.CODCLI = venda.CODCLI ORDER BY cliente.NOME;

select cliente.NOME, venda.DUPLIC, venda.VALOR FROM cliente, venda WHERE cliente.CODCLI = venda.CODCLI AND cliente.NOME LIKE '%PERMER%'

select cliente.NOME, venda.VENCTO FROM cliente, venda WHERE cliente.CODCLI = venda.CODCLI AND YEAR(venda.VENCTO) = 2022 AND MONTH(venda.VENCTO) = 4 ORDER BY venda.VENCTO