// <auto-generated />
using System;
using MVC_EF_CORE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_EF_CORE.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("MVC_EF_CORE.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("TipoSocioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoSocioId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("MVC_EF_CORE.Models.TipoSocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DuracaoEmMeses")
                        .HasColumnType("int");

                    b.Property<int>("taxaDesconto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TipoSocios");
                });

            modelBuilder.Entity("MVC_EF_CORE.Models.Aluno", b =>
                {
                    b.HasOne("MVC_EF_CORE.Models.TipoSocio", "TipoSocio")
                        .WithMany()
                        .HasForeignKey("TipoSocioId");

                    b.Navigation("TipoSocio");
                });
#pragma warning restore 612, 618
        }
    }
}
